---
- name: install gimme
  become: true
  get_url:
    url: https://raw.githubusercontent.com/travis-ci/gimme/master/gimme
    dest: /usr/local/bin/gimme
    mode: 'u=rwx,go=rx'

- name: set gimme for stable version
  command: gimme -r stable
  changed_when: false

- name: see if golang was already installed by gimme
  command: gimme -l
  register: result
  ignore_errors: true
  changed_when: false

- name: install golang
  command: gimme stable
  when: result.rc != 0

- name: make sure /etc/profile.d exists
  become: yes
  file:
    path: /etc/profile.d
    state: directory
    owner: root
    group: root
    mode: 'u=rwx,go=rx'

- name: export Go language SDK environment variables
  become: yes
  shell: |
   cp ./.gimme/envs/latest.env /etc/profile.d/golang.sh
   chmod 0644 /etc/profile.d/golang.sh
  args:
    creates: /etc/profile.d/golang.sh
